### ISSUE TITLE
How does Loess decide how many sub-intervals to use for local regression? 

### ISSUE THREAD

**Issue by Ayush-iitkgp** [JuliaStats/Loess.jl#20]
Hi, I asked this question on disourse but couldn't get any reply, hence posting it here for help.
I want to do local regression at each and every input point. For example:

```
using Loess
xs = sort(rand(100))   #100 input points
p = 1
ys = exp(p*tpoints) + 0.1 * rand(100)
model = loess(xs,ys)
```
when I do

`model.bs
`
I only get 2-D array of 33×3 dimension. I want to get b's for all points in xs (i.e 100×3 dimension). Is there a way to do it?

**Comment by Ayush-iitkgp** [comment]
Update - I am getting b's to be 100×3 dimension matrix by decreasing the value of `span to 0.05` but my values of b's are coming out to be negative which shouldn't be the case.

**Comment by ChrisRackauckas** [comment]
Well, instead of just the b's, where looking for the value and derivative predictions. It's probably okay if it's not at the same timepoints. It looks like we can get the values at the right points via `predict`, but I am not sure of a way to get the derivative out. What we were working from suggested using the b1 from a Loess because that's a derivative prediction at a specific spot, but as long as we have valid smoothed (x,x') values it's fine.

**Comment by ChrisRackauckas** [comment]
Yes, reading through the materials, what we really just need is a `predict` for the derivative values. Is this doable?

**Comment by ChrisRackauckas** [comment]
We can probably close this.
